version:  '3.7'
services:
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: example
        ports:
            - '33061:3306'
    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - './code/public:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8080:80'
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        user: 1000:1000
        links:
            - mysql:db