version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.20
      - image: mysql:8.0.16
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout

      - restore_cache:
          key: dependency

      - run:
          name: Install PHP extensions
          command: sudo -E docker-php-ext-install pdo_mysql sysvsem

      - run:
          name: Install Composer
          command: |
            cd /tmp
            EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
            if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
            then
                >&2 echo 'ERROR: Invalid installer signature'
                rm composer-setup.php
                exit 1
            fi
            sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
            RESULT=$?
            rm composer-setup.php
            exit $RESULT

      - run:
          command: composer install --ignore-platform-reqs --prefer-source --no-interaction
          working_directory: code

      - save_cache:
          key: dependency
          paths: code/vendor

      - run:
          command: ./bin/console doctrine:database:create --no-interaction -e test
          working_directory: code

      - run:
          command: ./bin/console doctrine:migrations:migrate --no-interaction -e test
          working_directory: code

      - run:
          command: ./bin/phpunit
          working_directory: code
